output_dir: output/

dataset:
  class: FB15k237LogicalQuery
  root: query-datasets/

model:
  class: UltraQuery
  model:
    class: Ultra
    relation_model:
      class: RelNBFNet
      input_dim: 64
      hidden_dims: [64, 64, 64, 64, 64, 64]
      message_func: distmult
      aggregate_func: sum
      short_cut: yes
      layer_norm: yes
    entity_model:
      class: QueryNBFNet
      input_dim: 64
      hidden_dims: [64, 64, 64, 64, 64, 64]
      message_func: distmult
      aggregate_func: sum
      short_cut: yes
      layer_norm: yes
  logic: product
  dropout_ratio: 0.25
  threshold: 0.0
  more_dropout: 0.0

task:
  name: TransductiveInference
  strict_negative: yes
  adversarial_temperature: 0.2
  sample_weight: no
  metric: [mrr, hits@1, hits@3, hits@10]

optimizer:
  class: Adam
  lr: 5.0e-4

train:
  gpus: {{ gpus }}
  batch_size: 32
  num_epoch: 10
  batch_per_epoch: 4000
  log_interval: 400
  fast_test: 1000

backbone_ckpt: {{ backbone_ckpt }}
query_ckpt: null
